name: CI/CD

on:
  - push
  - pull_request

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
    - uses: actions/checkout@v1
    - name: check effective user/groups and $HOME
      run: |
        whoami
        echo $HOME
    - name: check Debian version
      run: |
        cat /etc/debian_version
    - name: install sudo and moreutils (for chronic)
      run: |
        echo "Detected APT sources:"
        grep deb /etc/apt/sources.list /etc/apt/sources.list.d/* | grep -v ":#"
        apt update
        apt install --yes sudo moreutils
    - name: workaround failing git ownership check
      run: |
        apt install --yes git > /dev/null
        git config --global --add safe.directory '*'
    - name: install ikiwiki package
      run: |
        apt install --install-recommends --yes ikiwiki libimage-magick-perl
    - name: build
      run: |
        echo $PWD
        echo $HOME
        mkdir -p $HOME/smuxi-web.src
        ikiwiki --setup $PWD/ikiwiki.setup
        #ikiwiki --rebuild --setup $PWD/ikiwiki.setup
        # copy symlinked screenshot files into the build output as ikiwiki is skipping these
        cp -a $PWD/screenshots/* $PWD/smuxi-web.public_html/screenshots/
        # ikiwiki ignores plain HTML files, so we copy them here
        cp -a $PWD/download/start.html $PWD/smuxi-web.public_html/download/
    - name: seed SSH host pub key
      run: |
        mkdir -p $HOME/.ssh
        # fetch SSH host pub keys with 'ssh-keyscan nos.eu1.meebey.net'
        echo "nos.eu1.meebey.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCOmszqwtjW/wYHqtE9iYAVLdlZjTv7YC4vXmYCXrcB6BBVQdecg/v1cjzjRmBedAy/L4Woyg4ADEBlyW+hr704VPjgt8zY1SmF4nh7CzOOvV0n34cup6iplq1bzdjJvlS+xZYdG9lGyfu74hVu9OJCzXVbEBnhcgjfyhgVrqnvVtodr6vPIMvKKl05nHWDAZB01HKCLUE0zJ+VKTI5uAC7jDNqybmOyVTsw4vITiKukbwsD1ny+kiZeu6amGx3VdCQKgiz4cRx7QVTZoaD2IDWopENv4+yElR3cwlk7nq6VhUjAoN2l7/gvqhm2aN8q01Q4eQkfmDrGKrHMiLF/0KrY8TwNB+Kk5To9mNicPUkTd8TWDHgbGFkx5Li5tvuichUlelSdib7+V6AiWRS7l3I7MDNGLcQ6M/b+b/RKXNQ3aF87oOECfsjS+wUiiCHfl6NkMPr/qou6q8P1FAyBsw5Twn9aA3B5/6wrx/sH60fAoH0zKdCEruJYqj6MjOH7mPDKqRqeBvb3yuAIlDod4rsFWKrvgHR9KAQASUQFLYaAIWtp4yx07OLxFgCKRhrErJSgwk8PqYNFE3DxFlG3k+QzPXv0ZZlOk+vjcK/7wXfvCG1CoT8Tqu9JK7e/2Z9fIY9P8Z8ZfW42jXUvsKoF3Xe49eS6zYFr9EVZ7Qcy4RIow==" \
          >> $HOME/.ssh/known_hosts
        echo "nos.eu1.meebey.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPLLQmqhJzVkJcN2lDo1jum90Y6S6HO4XNBRHRiSuiLb" \
          >> $HOME/.ssh/known_hosts
    - name: make SSH private key available
      env: # expose variables via env block to prevent script injection
        GH_ACTION_DEPLOYMENT_SSH_PRIVATE_KEY: ${{ secrets.GH_ACTION_DEPLOYMENT_SSH_PRIVATE_KEY }}
      run: |
        touch $HOME/.ssh/id
        chmod 600 $HOME/.ssh/id
        echo "$GH_ACTION_DEPLOYMENT_SSH_PRIVATE_KEY" >> $HOME/.ssh/id
    - name: install rsync
      run: |
        apt install --yes rsync > /dev/null
    - name: deploy to nos
      run: |
        # -o UserKnownHostsFile=... is needed as ssh picks up /root as $HOME, while GitHub sets $HOME to /github/home, so ssh then looks for the wrong location
        # FIXME: scp skips symlinks!
        #scp -r -i $HOME/.ssh/id -o UserKnownHostsFile=$HOME/.ssh/known_hosts \
        #  $PWD/smuxi-web.public_html/* \
        #  github-actions_smuxi-web@nos.eu1.meebey.net:/srv/local/websites/smuxi.im/htdocs/
        rsync -e "ssh -v -l github-actions_smuxi-web -i $HOME/.ssh/id -o UserKnownHostsFile=$HOME/.ssh/known_hosts" \
          --stats -a \
          $PWD/smuxi-web.public_html/ \
          nos.eu1.meebey.net:
